[tool.poetry]
name = "draguilator"
version = "0.1.0"
description = "A dragons compiler implementation"
authors = ["Mateus Favarin Costa", "Robson Zagre Junior", "Wesly Carmesini Ataide"]

[tool.poetry.dependencies]
ply = "3.11"

