
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN BREAK COMMA COMMENT DEFINE DIVIDE ELSE EQUAL_TO FLOAT FLOAT_CONSTANT FOR GREATER_EQUAL_THAN GREATER_THAN IDENT IF INT INT_CONSTANT LBRACES LBRACKET LESS_EQUAL_THAN LESS_THAN LPAREN MINUS MODULO NEW NOT_EQUAL_TO NULL PLUS PRINT RBRACES RBRACKET READ RETURN RPAREN SEMICOLON STRING STRING_CONSTANT TIMESfunccall : IDENT LPAREN paramlistcall RPAREN\n    paramlistcall : IDENT _paramlistcall\n\t\t\t   | empty\n    _paramlistcall : COMMA paramlistcall\n\t\t\t   | empty\n    empty : '
    
_lr_action_items = {'IDENT':([0,3,8,],[2,4,4,]),'$end':([1,10,],[0,-1,]),'LPAREN':([2,],[3,]),'RPAREN':([3,4,5,6,7,8,9,11,],[-6,-6,10,-3,-2,-6,-5,-4,]),'COMMA':([4,],[8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'funccall':([0,],[1,]),'paramlistcall':([3,8,],[5,11,]),'empty':([3,4,8,],[6,9,6,]),'_paramlistcall':([4,],[7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> funccall","S'",1,None,None,None),
  ('funccall -> IDENT LPAREN paramlistcall RPAREN','funccall',4,'p_funccall','draguitax.py',14),
  ('paramlistcall -> IDENT _paramlistcall','paramlistcall',2,'p_paramlistcall','draguitax.py',21),
  ('paramlistcall -> empty','paramlistcall',1,'p_paramlistcall','draguitax.py',22),
  ('_paramlistcall -> COMMA paramlistcall','_paramlistcall',2,'p__paramlistcall','draguitax.py',28),
  ('_paramlistcall -> empty','_paramlistcall',1,'p__paramlistcall','draguitax.py',29),
  ('empty -> <empty>','empty',0,'p_empty','draguitax.py',35),
]
